# Generated by Django 6.1 on 2026-09-11 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0005_appointment_worker_completed_and_more'),
        ('services', '0003_add_deepa_service_catalog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(5, '★★★★★ (5/5) Excellent'), (4, '★★★★☆ (4/5) Very Good'), (3, '★★★☆☆ (3/5) Good'), (2, '★★☆☆☆ (2/5) Fair'), (1, '★☆☆☆☆ (1/5) Poor')], default=5)),
                ('comments', models.TextField(help_text='Customer review or feedback')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='appointments.appointment')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='services.service')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
