# Generated by Django 6.1 on 2026-09-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='sentiment',
            field=models.CharField(choices=[('POSITIVE', 'Positive'), ('NEUTRAL', 'Neutral'), ('NEGATIVE', 'Negative')], db_index=True, default='NEUTRAL', help_text='Automated sentiment classification (Positive, Neutral, Negative)', max_length=15),
        ),
        migrations.AddField(
            model_name='feedback',
            name='sentiment_score',
            field=models.FloatField(default=0.0, help_text='Polarity compound score (-1.0 to +1.0)'),
        ),
    ]
