# Generated by Django 6.0.7 on 2026-07-24 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['appointment_date', 'appointment_time']},
        ),
    ]
